-- -- MySQL
-- -- Criação do banco de dados
-- CREATE DATABASE DB_LOCADORA;
--
-- -- Criação das tabelas
-- CREATE TABLE DB_LOCADORA.TA_USUARIO (
--     ID_USUARIO INTEGER AUTO_INCREMENT,
--     EMAIL VARCHAR(255) NOT NULL,
--     NOME_COMPLETO VARCHAR(255) NOT NULL,
--     SENHA VARCHAR(255) NOT NULL,
--     PRIMARY KEY (ID_USUARIO),
--     UNIQUE (EMAIL)
-- );
--
-- CREATE TABLE DB_LOCADORA.TA_FILME (
--     ID_FILME INTEGER AUTO_INCREMENT,
--     TITULO VARCHAR(255) NOT NULL,
--     DIRETOR VARCHAR(255),
--     PRIMARY KEY (ID_FILME)
-- );
--
-- CREATE TABLE DB_LOCADORA.TA_INVENTARIO_FILME (
--     ID_INVENTARIO_FILME INTEGER AUTO_INCREMENT,
--     ID_FILME INTEGER NOT NULL,
--     ID_USUARIO INTEGER,
--     PRIMARY KEY (ID_INVENTARIO_FILME),
--     FOREIGN KEY (ID_FILME)
--         REFERENCES DB_LOCADORA.TA_FILME(ID_FILME),
--     FOREIGN KEY (ID_USUARIO)
--         REFERENCES DB_LOCADORA.TA_USUARIO(ID_USUARIO)
-- );

-- H2

-- DDL --

DROP TABLE IF EXISTS TA_INVENTARIO_FILME;
DROP TABLE IF EXISTS TA_FILME;
DROP TABLE IF EXISTS TA_USUARIO;

-- Criação das tabelas
CREATE TABLE TA_USUARIO (
    ID_USUARIO INTEGER AUTO_INCREMENT,
    EMAIL VARCHAR(255) NOT NULL,
    NOME_COMPLETO VARCHAR(255) NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID_USUARIO),
    UNIQUE (EMAIL)
);

CREATE TABLE TA_FILME (
    ID_FILME INTEGER AUTO_INCREMENT,
    TITULO VARCHAR(255) NOT NULL,
    DIRETOR VARCHAR(255),
    PRIMARY KEY (ID_FILME)
);

CREATE TABLE TA_INVENTARIO_FILME (
    ID_INVENTARIO_FILME INTEGER AUTO_INCREMENT,
    ID_FILME INTEGER NOT NULL,
    ID_USUARIO INTEGER,
    PRIMARY KEY (ID_INVENTARIO_FILME),
    FOREIGN KEY (ID_FILME)
        REFERENCES TA_FILME(ID_FILME),
    FOREIGN KEY (ID_USUARIO)
        REFERENCES TA_USUARIO(ID_USUARIO)
);

-- DML --

-- Filmes
INSERT INTO TA_FILME(TITULO, DIRETOR)
VALUES('Um Sonho de Liberdade', 'Frank Darabont');

INSERT INTO TA_FILME(TITULO, DIRETOR)
VALUES('Batman: O Cavaleiro das Trevas', 'Christopher Nolan');

INSERT INTO TA_FILME(TITULO, DIRETOR)
VALUES('O Senhor dos Anéis: O Retorno do Rei', 'Peter Jackson');

INSERT INTO TA_FILME(TITULO, DIRETOR)
VALUES('Coringa', 'Todd Phillips');

INSERT INTO TA_FILME(TITULO, DIRETOR)
VALUES('Matrix', 'Lana Wachowski');

-- Inventário de Filmes (Estoque)

INSERT INTO TA_INVENTARIO_FILME(ID_FILME)
VALUES (SELECT FILME.ID_FILME FROM TA_FILME FILME WHERE FILME.TITULO = 'Matrix');
INSERT INTO TA_INVENTARIO_FILME(ID_FILME)
VALUES (SELECT FILME.ID_FILME FROM TA_FILME FILME WHERE FILME.TITULO = 'Matrix');
INSERT INTO TA_INVENTARIO_FILME(ID_FILME)
VALUES (SELECT FILME.ID_FILME FROM TA_FILME FILME WHERE FILME.TITULO = 'Matrix');

INSERT INTO TA_INVENTARIO_FILME(ID_FILME)
VALUES (SELECT FILME.ID_FILME FROM TA_FILME FILME WHERE FILME.TITULO = 'Coringa');
INSERT INTO TA_INVENTARIO_FILME(ID_FILME)
VALUES (SELECT FILME.ID_FILME FROM TA_FILME FILME WHERE FILME.TITULO = 'Coringa');


INSERT INTO TA_INVENTARIO_FILME(ID_FILME)
VALUES (SELECT FILME.ID_FILME FROM TA_FILME FILME WHERE FILME.TITULO = 'Um Sonho de Liberdade');
INSERT INTO TA_INVENTARIO_FILME(ID_FILME)
VALUES (SELECT FILME.ID_FILME FROM TA_FILME FILME WHERE FILME.TITULO = 'Um Sonho de Liberdade');


INSERT INTO TA_INVENTARIO_FILME(ID_FILME)
VALUES (SELECT FILME.ID_FILME FROM TA_FILME FILME WHERE FILME.TITULO = 'O Senhor dos Anéis: O Retorno do Rei');


INSERT INTO TA_INVENTARIO_FILME(ID_FILME)
VALUES (SELECT FILME.ID_FILME FROM TA_FILME FILME WHERE FILME.TITULO = 'Batman: O Cavaleiro das Trevas');

-- Usuários(Clientes)

INSERT INTO TA_USUARIO(EMAIL, NOME_COMPLETO, SENHA)
VALUES('joao@teste.com', 'João Silva', 'XQW6+Ylns7+ENElKYvo79FA0tzCvL26x');

INSERT INTO TA_USUARIO(EMAIL, NOME_COMPLETO, SENHA)
VALUES('maria@teste.com', 'Maria Santos', 'XQW6+Ylns7+ENElKYvo79FA0tzCvL26x');

INSERT INTO TA_USUARIO(EMAIL, NOME_COMPLETO, SENHA)
VALUES('jose@teste.com', 'José Abreu', 'XQW6+Ylns7+ENElKYvo79FA0tzCvL26x');

COMMIT;