-- MySQL
-- Criação do banco de dados
CREATE DATABASE DB_LOCADORA;

-- Criação das tabelas

CREATE TABLE DB_LOCADORA.TA_USUARIO (
    ID_USUARIO INTEGER AUTO_INCREMENT,
    EMAIL VARCHAR(100) NOT NULL,
    NOME_COMPLETO VARCHAR(255) NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID_USUARIO),
    UNIQUE (EMAIL)
);

CREATE TABLE DB_LOCADORA.TA_FILME (
    ID_FILME INTEGER AUTO_INCREMENT,
    TITULO VARCHAR(150) NOT NULL,
    DIRETOR VARCHAR(255),
    PRIMARY KEY (ID_FILME)
);

CREATE TABLE DB_LOCADORA.TA_INVENTARIO_FILME (
    ID_INVENTARIO_FILME INTEGER AUTO_INCREMENT,
    ID_FILME INTEGER NOT NULL,
    ID_USUARIO INTEGER,
    PRIMARY KEY (ID_INVENTARIO_FILME),
    FOREIGN KEY (ID_FILME)
        REFERENCES DB_LOCADORA.TA_FILME(ID_FILME),
    FOREIGN KEY (ID_USUARIO)
        REFERENCES DB_LOCADORA.TA_USUARIO(ID_USUARIO)
);

-- DML --

USE DB_LOCADORA;

-- Filmes
INSERT INTO TA_FILME(TITULO, DIRETOR)
VALUES('Um Sonho de Liberdade', 'Frank Darabont');

INSERT INTO TA_FILME(TITULO, DIRETOR)
VALUES('Batman: O Cavaleiro das Trevas', 'Christopher Nolan');

INSERT INTO TA_FILME(TITULO, DIRETOR)
VALUES('O Senhor dos Anéis: O Retorno do Rei', 'Peter Jackson');

INSERT INTO TA_FILME(TITULO, DIRETOR)
VALUES('Coringa', 'Todd Phillips');

INSERT INTO TA_FILME(TITULO, DIRETOR)
VALUES('Matrix', 'Lana Wachowski');

-- Inventário de Filmes (Estoque)

INSERT INTO DB_LOCADORA.TA_INVENTARIO_FILME(ID_FILME)
 SELECT FILME.ID_FILME FROM DB_LOCADORA.TA_FILME FILME WHERE FILME.TITULO = 'Matrix';
INSERT INTO DB_LOCADORA.TA_INVENTARIO_FILME(ID_FILME)
 SELECT FILME.ID_FILME FROM DB_LOCADORA.TA_FILME FILME WHERE FILME.TITULO = 'Matrix';
INSERT INTO DB_LOCADORA.TA_INVENTARIO_FILME(ID_FILME)
 SELECT FILME.ID_FILME FROM DB_LOCADORA.TA_FILME FILME WHERE FILME.TITULO = 'Matrix';

INSERT INTO DB_LOCADORA.TA_INVENTARIO_FILME(ID_FILME)
 SELECT FILME.ID_FILME FROM DB_LOCADORA.TA_FILME FILME WHERE FILME.TITULO = 'Coringa';
INSERT INTO DB_LOCADORA.TA_INVENTARIO_FILME(ID_FILME)
 SELECT FILME.ID_FILME FROM DB_LOCADORA.TA_FILME FILME WHERE FILME.TITULO = 'Coringa';


INSERT INTO DB_LOCADORA.TA_INVENTARIO_FILME(ID_FILME)
 SELECT FILME.ID_FILME FROM DB_LOCADORA.TA_FILME FILME WHERE FILME.TITULO = 'Um Sonho de Liberdade';
INSERT INTO DB_LOCADORA.TA_INVENTARIO_FILME(ID_FILME)
 SELECT FILME.ID_FILME FROM DB_LOCADORA.TA_FILME FILME WHERE FILME.TITULO = 'Um Sonho de Liberdade';


INSERT INTO DB_LOCADORA.TA_INVENTARIO_FILME(ID_FILME)
 SELECT FILME.ID_FILME FROM DB_LOCADORA.TA_FILME FILME WHERE FILME.TITULO = 'O Senhor dos Anéis: O Retorno do Rei';


INSERT INTO DB_LOCADORA.TA_INVENTARIO_FILME(ID_FILME)
 SELECT FILME.ID_FILME FROM DB_LOCADORA.TA_FILME FILME WHERE FILME.TITULO = 'Batman: O Cavaleiro das Trevas';

-- Usuários(Clientes)

INSERT INTO DB_LOCADORA.TA_USUARIO(EMAIL, NOME_COMPLETO, SENHA)
VALUES('joao@teste.com', 'João Silva', 'XQW6+Ylns7+ENElKYvo79FA0tzCvL26x');

INSERT INTO DB_LOCADORA.TA_USUARIO(EMAIL, NOME_COMPLETO, SENHA)
VALUES('maria@teste.com', 'Maria Santos', 'XQW6+Ylns7+ENElKYvo79FA0tzCvL26x');

INSERT INTO DB_LOCADORA.TA_USUARIO(EMAIL, NOME_COMPLETO, SENHA)
VALUES('jose@teste.com', 'José Abreu', 'XQW6+Ylns7+ENElKYvo79FA0tzCvL26x');

COMMIT;